### ISSUE TITLE
XO load resistance

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Urukul#11]
Output current must be <=24mA according to the data sheet. Let's go for a total load of 150Ohm. With a 100R-50R divider, the peak-peak signal is still about 1V, which should be more than enough (particularly, since it's a square-wave output).

**Comment by jordens** [comment]
I think in practice it was actually more than that. When I looked at it on a scope I was actually worried about it being too much.

**Comment by hartytp** [comment]
Currently, we have a 50R-50R divider, so I'd expect more like 1.65Vp-p. Did you see more than that?

**Comment by gkasprow** [comment]
No we have 100:50 divider.
