### ISSUE TITLE
dnp screening clips

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Urukul#14]
@gkasprow not that it's a big deal, but didn't we agree to dnp the screening clips for v1.3 Our creotech boards still have them.

**Comment by gkasprow** [comment]
@hartytp yes, we did. I updated BOMs after the production started and that's why they mounted it. I should have changed the revision after BOM update.

**Comment by hartytp** [comment]
Ok. Makes sense. Can we make sure that Creotech know to dnp them in any future production runs please?

**Comment by gkasprow** [comment]
I asked them to use recent documentation just before production.
