### ISSUE TITLE
consistent LED sizes

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Urukul#17]
The front panel LEDs on Urukul are larger than all the others boards AFAICT. I am OK with Kasli being an exception in LED size, mounting and location (for space reasons). But Urukul should get LEDs similar in size to those on the other boards.

**Comment by gkasprow** [comment]
We should definitely standardize aesthetics of the modules. So I fully agree.
The front panels are made for each revision anyway so there won't be any cost issues.

**Comment by jordens** [comment]
I really like the edge emitting LEDs on the PCB bottom (Kasli, Humpback). That's an excellent use of space, they are surface mount, high density.

**Comment by gkasprow** [comment]
The only drawback is aesthetics. LEDs are visible from a very narrow angle. There are miniature 1mm light pipes that can be inserted to the holes in the panel so the user experience would be much better.

**Comment by jordens** [comment]
Yes. If those light pipes could be press fit into the panel that would be great.

**Comment by gkasprow** [comment]
replaced with LED_DIALIGHT_571-0112F
