### ISSUE TITLE
crystal oscillator availability

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Urukul#18]
@hartytp @jordens The lead time for CCHD-950-25-100.000  is 8 weeks or more.
What if we add assembly option for CCHD-950-25-100.000 and mount VCXO VHD-950-100.000 instead. This needs voltage divider on control pin that sets 1.65V to get nominal frequency.
Is 50ppm frequency stability acceptable? If yes, we can mount CCHD-950-50-100.000.

**Comment by jordens** [comment]
I think we could generally go to a slightly noisier crystal at the same accuracy level. E.g. in that smaller, more standard package. Probably easier and cheaper and if low noise and or high accuracy is needed it would come from mmcx or sma anyway.

**Comment by hartytp** [comment]
I'd be fine with using a different oscillator with worse performance but better availability.

**Comment by gkasprow** [comment]
OK, we will add it in ext revision, here will mount 50ppm oscillators.

**Comment by jordens** [comment]
Or the B grade of the Si510 like the one we use on Kasli.

**Comment by gkasprow** [comment]
added both resistive divider and Si510 3V3 30ppm footprint DNP by default

**Comment by gkasprow** [comment]
I found by chance perfect [replacement](https://www.taitien.com/wp-content/uploads/2019/07/XO-0171_VLEU.pdf) for Crystek oscillators
