### ISSUE TITLE
pull OSK high

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Urukul#19]
The ASF register is currently useless in Urukul. The OSK pin is pulled low and thus in manual mode ASF will be zero, and in automatic mode it will always ramp down. The ASF register is a nice feature for RAM operation.
Let's pull OSK high in the next revision. I can't see a downside to it.

**Comment by jordens** [comment]
Currently for FTW or POW RAM mode the only possible ASF is full scale.

**Comment by gkasprow** [comment]
I pulled it up to P3V3_DVDD_IO
