### ISSUE TITLE
SMA stackup wrong, SMA cables loose

### ISSUE THREAD

**Issue by Jochenwolf3** [sinara-hw/Urukul#24]
Using standard SMA cables (e.g. JP1XJP1XF316-40 from Gigatronix), there is not enough exposed threading to put the SMA cables on. The plastic washer, tooth washer, and nut take up so much space on the thread that upon tightening the SMA cable nut, the cable still feels loose and can be wiggled around, indicating an unreliable connection:

![20190408_142321](https://user-images.githubusercontent.com/32742764/55727639-56909700-5a0a-11e9-8576-683835cb38c3.jpg)

An extra ~3 mm of SMA threading is needed.

Workaround: remove the plastic washer from the stack, which creates just about enough space (and is fine for people who do not want their SMAs floated anyway)

**Comment by Jochenwolf3** [comment]
This applies to Urukuls manufactured by both Creotech and Technosystem.

**Comment by gkasprow** [comment]
One option is to switch to longer SMA connectors like Telegartner J01151A0921. But they are very long.
They are also far more expensive (30$/pc). 
 I can also move the PCB edge to the panel by 1mm. This should solve the issue.

**Comment by gkasprow** [comment]
I moved them by 1mm to the panel.
