### ISSUE TITLE
Ic18 drop out

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Urukul#32]
Are you definitely happy with the drop voltage for IC18? We don't quite hit the recommended 3.25V for Vbias-Vo (particularly when tolerances are accounted for) so it seems a bit marginal to me from the data sheet...

**Comment by hartytp** [comment]
Well, maybe it's okay at the currents we're operating at?

**Comment by gkasprow** [comment]
We can always switch to 7V5

**Comment by gkasprow** [comment]
ah, max bias is 5.5V

**Comment by gkasprow** [comment]
We can also slighty increase the 2V rail.

**Comment by gkasprow** [comment]
I increased the P2V0 rail to P2V1 to satisfy Vbias requirements.

**Comment by hartytp** [comment]
Sounds good. The small change in power efficiency is worth it to make sure the LDO functions as expected.

Did you make sure to update the power budget table?

**Comment by gkasprow** [comment]
done
![obraz](https://user-images.githubusercontent.com/4325054/63949271-69b80800-ca7a-11e9-9b2a-684141d94f1e.png)
