### ISSUE TITLE
Fix washer stack up

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Urukul#46]
https://github.com/sinara-hw/meta/issues/4
https://github.com/sinara-hw/Urukul/issues/45#issuecomment-587478088

**Comment by gkasprow** [comment]
what if we design and 3D print dedicated spacers that will fill the gap between the panel and the SMA? In this way, it will provide mechanical fixing to the panel without the need of using the nut.

**Comment by jordens** [comment]
Yes. Just a sleeve should be fine IMO. Like one of the original white plastic washers on the inside between SMA and panel, just with a bit more depth to be flush with the outside of the panel.

**Comment by gkasprow** [comment]
Here we are.
![2020-04-30 23 12 09](https://user-images.githubusercontent.com/4325054/80765211-c2c4c800-8b42-11ea-9ff7-cd9cfa53cde4.jpg)
![2020-04-30 23 12 17](https://user-images.githubusercontent.com/4325054/80765228-cb1d0300-8b42-11ea-8981-fee6eb73ef72.jpg)

**Comment by gkasprow** [comment]
the files are here:

[MECH.zip](https://github.com/sinara-hw/Urukul/files/4561704/MECH.zip)

**Comment by gkasprow** [comment]
we use 3D washers for some time so let's close it.
