### ISSUE TITLE
Consider adding TLT balun foot print

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Urukul#47]
Optional to consider for v1.5:

> We've modified a couple boards to use the third Nyquist image. That works fine apart from the balun being out of its depth. It would be nice to have a alternative footprint for a TLT balun in that standard smaller case style.

**Comment by jordens** [comment]
[TC1-1T-152X+](https://www.minicircuits.com/pdfs/TC1-1T-152X+.pdf) I think

**Comment by dhslichter** [comment]
+1 to this idea in general.  @jordens is the reason for choosing this part just for pin compatibility with existing pads (i.e. no change in copper necessary)?

**Comment by jordens** [comment]
It's actually different pads than the current footprint. But that case and pinout is pretty generic from what I could tell and would allow going to a cheaper/more commonly available package for the standard 1-500 MHz balun style as well.
That TLT part number is the only one that I could find that would work with the required biasing topology straight away (center tap).

**Comment by dhslichter** [comment]
p.s. the existing balun ADT1-1WT+ is a 75 ohm nominal balun...given that we're playing fast and loose with nominal impedances, has anyone tried dropping in an ADTL2-18+, which is pin compatible, nominal 50 ohm impedance but 2x transform, to see if the output is reasonable?

**Comment by dhslichter** [comment]
@jordens we need a center tap bias?  I guess I missed that.

**Comment by dhslichter** [comment]
Or is that just for the 9912, seems that the 9910 sets its dc level using the load resistors, right?

**Comment by jordens** [comment]
Both are center tap grounded on the eval boards. See #40, #39, #43 for more info and questions on that topic.

**Comment by jordens** [comment]
Maybe there are other topologies that don't blow up at DC (i.e. when FTW=0) and still bias/terminate fine.

**Comment by dhslichter** [comment]
> Both are center tap grounded on the eval boards. 

Weird.  Anyway, I am not trying to come in and blow things up, nor is there time for discussion on this given the urgency of putting at v1.5 release out today.  I'm just a little curious/surprised at AD for the eval board choices for the reasons discussed in #40

**Comment by gkasprow** [comment]
dual footprint is not that trivial here. Let's drop it for v1.5
![obraz](https://user-images.githubusercontent.com/4325054/74789611-827cda00-52b5-11ea-8f5e-5eebfafa75c7.png)

**Comment by jordens** [comment]
Ack

**Comment by hartytp** [comment]
Does anyone want to keep this open or shall we close?

**Comment by jordens** [comment]
We should keep this open.

**Comment by gkasprow** [comment]
I managed to slightly recuce the original balun pad width and place the second TLT balun
![obraz](https://user-images.githubusercontent.com/4325054/108513882-74e0a280-72c3-11eb-80a1-4941569d8bb3.png)
