### ISSUE TITLE
pre-amp bypass

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Urukul#48]
Only if easy to do: add a DNPd 0R resistor pad to allow us to bypass (and DNP) the pre-amp as a population variant if desired.

**Comment by gkasprow** [comment]
![obraz](https://user-images.githubusercontent.com/4325054/74787771-4d21bd80-52b0-11ea-8eba-69261076ade8.png)
![obraz](https://user-images.githubusercontent.com/4325054/74787841-76424e00-52b0-11ea-8fee-69c13bcbb4ab.png)

**Comment by hartytp** [comment]
That resistor package very slightly decreases the gap between the input and output pins of the preamp. I assume that since it’s onlu a 3GHz gain block we’re not worried about that (the 20GHz mmics can be quite sensitive to layout).
