### ISSUE TITLE
Output un-uns

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Urukul#49]
Only if this can be done without major rework or compromises on the layout: add a footprint for DNPd un-uns (e.g. TC1-1(T)(X)(+)) on the outputs. The idea of these (please add a schematic annotation documenting this) is to provide the possibility of breaking ground loops (in that case the "grounding" capacitors should be DNPd or possibly even just removed from the design).

**Comment by gkasprow** [comment]
![obraz](https://user-images.githubusercontent.com/4325054/74789149-25ccef80-52b4-11ea-9734-0ad21fad937b.png)
![obraz](https://user-images.githubusercontent.com/4325054/74789197-485f0880-52b4-11ea-882a-78ca7f167629.png)

**Comment by hartytp** [comment]
Lgtm. Only comment is that I wonder if a bigger resistor package for the 0R would keep the gap between the input and output pins of the un un a bit wider. I don’t see this causing problems in practice however
