### ISSUE TITLE
Support cPCIs backplane

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Urukul#51]
Place jumpers between MMCX clock in and Samtec hermaphroditic (https://github.com/sinara-hw/Phaser/issues/74#issue-527610429)

**Comment by gkasprow** [comment]
Adding the Samtec connector is a lot of work. The CPLD mus be moved and re-routed. Let's leave it for the next release.
![obraz](https://user-images.githubusercontent.com/4325054/74873319-42723180-535f-11ea-9345-309aef5993a5.png)

**Comment by jordens** [comment]
Sure. Just wanted to put it on the list for the next revision.

**Comment by gkasprow** [comment]
btw, this is how the CPCIS version of Urukul will look like
https://autode.sk/38NAshC

**Comment by gkasprow** [comment]
We don't have many boards with these clock connectors, I decided to move it close to EEM connectors to save some space. Next Phaser/Mirny release will have it also moved closer to the edge.
