### ISSUE TITLE
incorrect PCB stackup dielectric constant

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Urukul#54]
The Dielectric3 layer constant is specified to be 4.2, which is not symmetric (the constant of Dielectric1 is 3.66). And the theoretical impedances improve when changing the constant of Dielectric3 to 3.66. Greg confirmed this is an error.

![urukul_stackup](https://user-images.githubusercontent.com/720864/103115386-52545380-469d-11eb-8500-92aaa5e482c8.png)

**Comment by gkasprow** [comment]
fixed
