### ISSUE TITLE
DC floating section

### ISSUE THREAD

**Issue by dtcallcock** [sinara-hw/Urukul#57]
The section between C49 and C50 has an undefined DC potential.  I always thought this was to be avoided. Though I can't find a good reference for why this is bad right now  (dC/dV of caps?, making an antenna?), so I am happy for someone to tell me it doesn't matter.  Solution would be a BOM change to make default C50 population a 0R.

<img width="529" alt="image" src="https://user-images.githubusercontent.com/20587606/112888960-e0b7e700-9089-11eb-8f1a-03c2b099ec39.png">

**Comment by gkasprow** [comment]
At least such configuration cannot be simulated using SPICE:)
I don't know any mechanism that caps could build-up DC voltage causing significant change to their capacitance.

**Comment by dhslichter** [comment]
agreed that default BOM change to make C50 a 0R would be the way to go here.

**Comment by dtcallcock** [comment]
Despite my failure to articulate much beyond 'it gives me bad feelings', I don't think there is any good reason **TO** have two caps in series like this.  But obviously can wait until BOM needs changing anyway.

**Comment by gkasprow** [comment]
fixed
