### ISSUE TITLE
Attenuator DC block cap

### ISSUE THREAD

**Issue by dtcallcock** [sinara-hw/Urukul#58]
There is no DC blocking cap on input of IC3.

<img width="917" alt="image" src="https://user-images.githubusercontent.com/20587606/112890154-5ec8bd80-908b-11eb-98ce-ad43632261af.png">

From IC3 [datasheet](https://www.analog.com/media/en/technical-documentation/data-sheets/hmc542b.pdf):

![image](https://user-images.githubusercontent.com/20587606/112890225-77d16e80-908b-11eb-9199-4239cf453672.png)

Was this an oversight or does the DC GND path provided by FL2+TR1 mean we don't need this (though if this is the case, you could probably make a similar argument for the output blocking cap given the next component is an attenuator that has a DC path to GND)?

**Comment by gkasprow** [comment]
Good point. Some switches have an internal charge pump and can work with GND-referenced signals. In our case lack of caps can induce nonliearities.

**Comment by jordens** [comment]
The jumper decouples.

**Comment by dtcallcock** [comment]
Ok, now I spot the reference to 'C28' in this comment.

<img width="246" alt="image" src="https://user-images.githubusercontent.com/20587606/112902302-c5090c80-909a-11eb-9824-2c5ec002081c.png">

But AFAICT, C28's location or value aren't on the schematic.  Can the ambiguities of the 'mystery red box' easily be fixed?  If not then more clarity in the comment would help.

**Comment by gkasprow** [comment]
I added a comment 
![obraz](https://user-images.githubusercontent.com/4325054/129414676-296e3569-c1ea-45f0-b6df-4fb5c99341ad.png)

**Comment by gkasprow** [comment]
I also changed the frame around components so the values will be visible in pdf
