### ISSUE TITLE
IC22 voltage

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Urukul#60]
I've just noticed that IC22 has a "0.8V" annotation close to the FB input.
In fact, it should be 0.7V. The TPS62148 is able to deliver output from 0.8V but the nominal FB voltage is 0.7V
With current resistors, it produces 6.5 instead of 7.5V which makes the 7V LDO out of regulation.
Can somebody who has Urukul measure the voltage on C211?
![obraz](https://user-images.githubusercontent.com/4325054/116236276-276b3080-a75f-11eb-910a-4bbe8e1ab25f.png)

**Comment by jordens** [comment]
Isn't this https://github.com/sinara-hw/Urukul/issues/20 ?

**Comment by atcher0** [comment]
Voltage measured on C211: 6.58 V (I checked on two different Urukul AD9910 v1.5.1 boards). It produces about 6.33 V from the IC21 LDO.

**Comment by gkasprow** [comment]
R134=75k
R136=7k5

**Comment by gkasprow** [comment]
fixed in v1.5.2

**Comment by dnadlinger** [comment]
What's the practical consequence of this being left unpatched? Worse output power stability?
