### ISSUE TITLE
Urukul layout

### ISSUE THREAD

**Issue by maciejprzybysz** [sinara-hw/Urukul#72]
We made some investigation on Urukul v1.5.3 and found some issues on layout and signal integrity.

1. DDS0_SYNC_IN/OUT signals (layer L3) have poor reference on L2 layer. 

   ![2023-03-27_13h54_22](https://user-images.githubusercontent.com/48446953/227944235-2c57b326-a6d6-46fa-a5cc-f40961d66786.png)

2. Also other DDSx_SYNC_x signals have problem with reference, due to specifics of stackup. In general L2 should be reference for L1(TOP) and L3 signal layers, P5 should be reference for L4 and L6(BOT). In fact dielectric thickness between L3 and L4 is much lower than between L2/L3 or L4/L5, so there is strong coupling between 2 center layers. 

   ![2023-03-27_13h59_08](https://user-images.githubusercontent.com/48446953/227945471-d18a007a-a63a-4ae0-ba8b-3477b1a492a3.png)

   DDSx_SYNC_x signals on layer L4 on the background of layer L3 looks like this:
   ![2023-03-27_14h10_32](https://user-images.githubusercontent.com/48446953/227945746-38ae4424-6e09-41e6-abe7-5043992278bd.png)
   ![2023-03-27_14h11_00](https://user-images.githubusercontent.com/48446953/227945761-d369ea34-274d-4386-be81-8201cacaec18.png)
   ![2023-03-27_14h11_25](https://user-images.githubusercontent.com/48446953/227945768-6b74ce88-3a07-4a25-ad72-d3e90423cff7.png)
   ![2023-03-27_14h11_44](https://user-images.githubusercontent.com/48446953/227945773-4b073535-7df8-4827-bb32-1b1ac3faef18.png)

   This could cause step changes in impedance and signal integrity problems.
<br>

3. ORIGIN. This issues affect Urukul v1.4 and later.

   Till v1.3 L2 was mostly GND split plane, there wasn't any signals there, so DDS0_SYNC_IN/OUT had good reference.
   ![2023-03-27_14h33_05](https://user-images.githubusercontent.com/48446953/227946862-6cb0b4b1-30ba-43b4-ac1d-33398ce455d0.png)

   In addition, there was no GND plane on L3 and L4 layers, so the only reference for DDSx_SYNC_x signals was on L2 or L5 layer. 
![2023-03-27_14h37_50](https://user-images.githubusercontent.com/48446953/227946875-421473fe-14a5-4be4-b0dd-f0a9527a887e.png)

**Comment by gkasprow** [comment]
that's strange. Usually when designing 6 layer boards I treat them as two 3-layer boards having L3-L4 separation dominating so L3 and L4 impedances are defined by thin dielectric to L2 and L5.
These issues can be easily fixed by changing stackup and re-routing these two lines which don't have valid reference on L2.
I don't think however that this is the main issue why we don't have synchronization.  in v1.4 we swtiched to another CPLD in bigger package

**Comment by gkasprow** [comment]
fixed in v1.5.5

**Comment by marmeladapk** [comment]
Mostly fixed, remaining problems are in a separate issues.
