### ISSUE TITLE
Add vias for reference layer change

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/Urukul#74]
- [x] DDS0_SYNC_{IN,OUT}:
![Zrzut ekranu z 2023-06-23 16-20-41](https://github.com/sinara-hw/Urukul/assets/24512604/8eede11c-e9ab-47c9-9dbc-07f4317595b1)

- [x] DDS1_SYNC_IN:
![Zrzut ekranu z 2023-06-23 16-38-31](https://github.com/sinara-hw/Urukul/assets/24512604/b02099da-864f-48f7-9348-d6ebb22b7d0f)

- [x] DDS2_SYNC_IN:
![Zrzut ekranu z 2023-06-23 16-31-47](https://github.com/sinara-hw/Urukul/assets/24512604/2339e2aa-a1b9-40ae-af8e-08bd2b245f28)

- [x] DDS3_SYNC_IN:
![Zrzut ekranu z 2023-06-23 16-33-05](https://github.com/sinara-hw/Urukul/assets/24512604/4aa883c8-6070-45db-b3db-673c70320a5d)

- [x] CK_OSC:
![Zrzut ekranu z 2023-06-23 16-46-00](https://github.com/sinara-hw/Urukul/assets/24512604/cc9eb411-917c-42eb-a98b-c71a2a348fe9)

- [x] CK_MMCX
![Zrzut ekranu z 2023-06-23 16-53-58](https://github.com/sinara-hw/Urukul/assets/24512604/9266cc55-3be2-4049-89c9-0abaee6374ef)

- [x] DDS_CLKA, DDS_CLKB, DDS_CLKB0:
![Zrzut ekranu z 2023-06-23 17-02-01](https://github.com/sinara-hw/Urukul/assets/24512604/12e88a48-3139-4a32-baf1-63a06b66f6c1)

**Comment by gkasprow** [comment]
I added GND vias where I could fit them
