### ISSUE TITLE
Via tenting

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/Urukul#76]
- [x] Untent vias in IC9
- [x] Tent selected vias:
![Zrzut ekranu z 2023-06-23 17-13-26](https://github.com/sinara-hw/Urukul/assets/24512604/49fc2001-dcfa-4646-a40a-614d0a2ea60f)
![Zrzut ekranu z 2023-06-23 17-14-30](https://github.com/sinara-hw/Urukul/assets/24512604/46bd4926-6bb5-4245-a0da-3936bb41a115)

**Comment by gkasprow** [comment]
IC9 is already untented 
![image](https://github.com/sinara-hw/Urukul/assets/4325054/6ed4912a-ae19-44e4-812c-dde855155415)

**Comment by marmeladapk** [comment]
This via is still untented:
![Zrzut ekranu z 2023-06-26 11-50-52](https://github.com/sinara-hw/Urukul/assets/24512604/359889c5-9178-42d6-87e6-7a2a512bf4ff)

**Comment by gkasprow** [comment]
fixed
