### ISSUE TITLE
Many broken xSignals

### ISSUE THREAD

**Issue by maciejprzybysz** [sinara-hw/Urukul#79]
I don't know if that can cause inconsistency in rules or not, but it would be nice to have the correct xSignals in the project anyway.
![2023-06-27_15h06_30](https://github.com/sinara-hw/Urukul/assets/48446953/febedcf1-aa36-4a39-8495-49a08e11b046)

**Comment by gkasprow** [comment]
which AD version are you using?

**Comment by marmeladapk** [comment]
In 23.6 these signals are indeed broken.

**Comment by gkasprow** [comment]
No faintest idea why it reports them as broken. I rerouted some of them and they are still broken at specified IC pad. Looks like yet another AD bug.

**Comment by gkasprow** [comment]
I see them broken as well but no idea why. Re-routing doesn't help.

**Comment by maciejprzybysz** [comment]
> which AD version are you using?

v23.6 also

Unfortunately, the only method that works for me is to delete broken xSignals and generate them again. If you change xSignals names, you need to change rules accordingly of course.

**Comment by gkasprow** [comment]
It seems these errors were introduced during Altium version transition.

**Comment by maciejprzybysz** [comment]
I think there are also some xSignals wrong defined:

![2023-06-28_12h04_50](https://github.com/sinara-hw/Urukul/assets/48446953/e6f6eb15-569b-43e3-9540-bd6ce088cc2a)

Moreover, according to notes on the schematic, these lines should be matched lenghts but no DRC error is reported.

**Comment by marmeladapk** [comment]
Yeah, rfsw signals to cpld are also meant to be length matched but xsignal class dissapeared.
